# Generated by Django 5.2.13 on 2026-04-23 23:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('correo_institucional', models.EmailField(help_text='Correo institucional para login (ej: usuario@uta.edu.ec)', max_length=254, unique=True)),
                ('carrera', models.CharField(blank=True, help_text='Carrera o programa académico', max_length=100, null=True)),
                ('numero_contacto', models.CharField(blank=True, help_text='Número de teléfono o celular', max_length=20, null=True)),
                ('zona_referencia', models.CharField(blank=True, help_text='Zona o barrio de referencia', max_length=100, null=True)),
                ('foto_perfil', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='perfil_photos/')),
                ('verificado', models.BooleanField(default=False, help_text='¿El usuario ha verificado su correo institucional?')),
                ('codigo_verificacion', models.CharField(blank=True, help_text='Código de 6 dígitos para verificar correo', max_length=6, null=True)),
                ('reputacion', models.FloatField(default=5.0, help_text='Puntuación promedio de reputación (0-5 estrellas)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('cantidad_viajes', models.IntegerField(default=0, help_text='Cantidad total de viajes completados')),
                ('advertencias', models.IntegerField(default=0, help_text='Cantidad de advertencias acumuladas')),
                ('suspendido_hasta', models.DateTimeField(blank=True, help_text='Fecha hasta la cual el usuario está suspendido (None si no está suspendido)', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['-fecha_creacion'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Marca del vehículo (ej: Toyota)', max_length=50)),
                ('modelo', models.CharField(help_text='Modelo del vehículo (ej: Corolla)', max_length=50)),
                ('ano', models.IntegerField(help_text='Año del vehículo')),
                ('color', models.CharField(help_text='Color del vehículo', max_length=30)),
                ('placa', models.CharField(help_text='Placa del vehículo (única)', max_length=10, unique=True)),
                ('capacidad_asientos', models.IntegerField(help_text='Capacidad total de pasajeros (incluyendo conductor)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(help_text='Conductor propietario del vehículo', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
            },
        ),
    ]
