# Generated by Django 5.2.13 on 2026-05-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_recuperacion',
            field=models.CharField(blank=True, help_text='Código de 6 dígitos para recuperar contraseña', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_expiracion_recuperacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de expiración del código de recuperación', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_institucional',
            field=models.EmailField(help_text='Correo institucional para login (ej: usuario@uta.edu.ec)', max_length=254, unique=True),
        ),
    ]
