# Generated by Django 5.2.13 on 2026-04-23 23:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(help_text='Puntuación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('resena', models.TextField(blank=True, help_text='Reseña opcional sobre la experiencia', null=True)),
                ('tipo', models.CharField(choices=[('Conductor a Pasajero', 'Conductor a Pasajero'), ('Pasajero a Conductor', 'Pasajero a Conductor')], help_text='Tipo de calificación', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evaluado', models.ForeignKey(help_text='Usuario que recibe la calificación', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(help_text='Usuario que realiza la calificación', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(help_text='Viaje en el que se produce la calificación', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='trips.viaje')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificacion',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('viaje', 'evaluador', 'evaluado')},
            },
        ),
    ]
