# Generated by Django 5.2.13 on 2026-04-23 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_advertencias', models.IntegerField(default=3, help_text='Número de advertencias antes de suspender')),
                ('dias_suspension', models.IntegerField(default=7, help_text='Días de suspensión por cada advertencia')),
                ('reglas_seguridad', models.TextField(default='1. Respetar horarios acordados.\n2. Comportamiento cordial.\n3. Cuidado del vehículo.', help_text='Reglas de seguridad del sistema')),
                ('edad_minima', models.IntegerField(default=18, help_text='Edad mínima permitida')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
        migrations.CreateModel(
            name='HistorialEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Registro', 'Registro'), ('Login', 'Login'), ('Viaje Creado', 'Viaje Creado'), ('Viaje Cancelado', 'Viaje Cancelado'), ('Solicitud Aceptada', 'Solicitud Aceptada'), ('Solicitud Rechazada', 'Solicitud Rechazada'), ('Calificación', 'Calificación'), ('Reporte', 'Reporte'), ('Advertencia', 'Advertencia'), ('Suspensión', 'Suspensión'), ('Otro', 'Otro')], help_text='Tipo de evento', max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción del evento')),
                ('detalles', models.JSONField(blank=True, help_text='Detalles adicionales en formato JSON', null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(help_text='Usuario involucrado en el evento', on_delete=django.db.models.deletion.CASCADE, related_name='historial_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Evento',
                'verbose_name_plural': 'Historial de Eventos',
                'db_table': 'historial_eventos',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('Conducta agresiva', 'Conducta agresiva'), ('Incumplimiento de reglas', 'Incumplimiento de reglas'), ('Mala condición del vehículo', 'Mala condición del vehículo'), ('Abuso o acoso', 'Abuso o acoso'), ('Daños a vehículo', 'Daños a vehículo'), ('Llegada tardía', 'Llegada tardía'), ('No presentarse', 'No presentarse'), ('Otro', 'Otro')], help_text='Motivo del reporte', max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción detallada del incidente')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En revisión', 'En revisión'), ('Resuelto', 'Resuelto')], default='Pendiente', help_text='Estado del reporte', max_length=20)),
                ('accion_tomada', models.CharField(blank=True, help_text='Acción tomada (advertencia, suspensión, etc.)', max_length=200, null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, help_text='Fecha en que se revisó el reporte', null=True)),
                ('reportado', models.ForeignKey(help_text='Usuario siendo reportado', on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('reportador', models.ForeignKey(help_text='Usuario que realiza el reporte', on_delete=django.db.models.deletion.CASCADE, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, help_text='Administrador que revisó el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_revisados', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(blank=True, help_text='Viaje asociado al reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='trips.viaje')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reporte',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
