# Generated by Django 5.2.13 on 2026-04-23 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_origen', models.CharField(help_text='Zona o barrio de origen', max_length=100)),
                ('zona_destino', models.CharField(help_text='Zona o barrio de destino', max_length=100)),
                ('fecha_hora_salida', models.DateTimeField(help_text='Fecha y hora de salida')),
                ('cupos_totales', models.IntegerField(help_text='Cantidad total de cupos (sin incluir conductor)')),
                ('cupos_disponibles', models.IntegerField(help_text='Cupos disponibles en el momento')),
                ('notas_reglas', models.TextField(blank=True, help_text='Notas o reglas especiales del viaje', null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('En Curso', 'En Curso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Activo', help_text='Estado actual del viaje', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(help_text='Conductor del viaje', on_delete=django.db.models.deletion.CASCADE, related_name='viajes_como_conductor', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, help_text='Vehículo usado en el viaje', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vehiculo')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'db_table': 'viaje',
                'ordering': ['-fecha_hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada')], default='Pendiente', help_text='Estado de la solicitud', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, help_text='Fecha en que el conductor respondió', null=True)),
                ('pasajero', models.ForeignKey(help_text='Pasajero que solicita', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_viajes', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(help_text='Viaje solicitado', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_pasajeros', to='trips.viaje')),
            ],
            options={
                'verbose_name': 'Solicitud de Viaje',
                'verbose_name_plural': 'Solicitudes de Viaje',
                'db_table': 'solicitud_viaje',
                'ordering': ['-fecha_solicitud'],
                'unique_together': {('viaje', 'pasajero')},
            },
        ),
    ]
